# Generated by Django 3.2.6 on 2021-11-23 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_auto_20211118_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=18)),
                ('cvc', models.CharField(max_length=3)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='predict.client')),
            ],
            options={
                'db_table': 'client_card',
                'managed': True,
            },
        ),
    ]
