# Generated by Django 3.2.6 on 2021-11-30 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_clientcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='couple_removed_at',
        ),
        migrations.CreateModel(
            name='CoupleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couple_added', models.DateTimeField(auto_now_add=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='predict.couple')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='predict.subscription')),
            ],
            options={
                'db_table': 'couple_history',
                'managed': True,
            },
        ),
    ]
