# Generated by Django 3.2.6 on 2021-12-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0005_auto_20211130_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='intervals',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
