# Generated by Django 3.2.6 on 2021-12-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0006_couple_intervals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientCard',
        ),
    ]
