# Generated by Django 3.2.6 on 2021-12-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0007_delete_clientcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='customers_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
