# Generated by Django 3.2.6 on 2021-12-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0009_subscription_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_method_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
