# Generated by Django 3.2.6 on 2021-12-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0010_subscription_payment_method_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couple',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
