# Generated by Django 3.2.6 on 2022-01-04 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0012_client_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDowngrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, null=True)),
                ('renew', models.DateTimeField()),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('total_discount', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method_id', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='predict.client')),
                ('couples', models.ManyToManyField(blank=True, null=True, to='predict.Couple')),
                ('subscribe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='predict.subscribe')),
            ],
            options={
                'db_table': 'client_downgrade',
                'managed': True,
            },
        ),
    ]
