# Generated by Django 3.2.6 on 2022-01-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0013_clientdowngrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_at', models.DateTimeField(auto_now_add=True)),
                ('sender_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sms',
                'managed': True,
            },
        ),
    ]
