CLIENT_NOT_FOUND = "Client not found"
UPDATE_SUCCESSFUL = "Update successful"
DELETE_SUCCESSFUL = "Delete successful"
TOKEN_EXPIRED = "Token expired"
DEFAULT_MAIL = "@default.com"
SUBSCRIBE_NOT_FOUND = "Subscribe not found"
REWARD_NOT_FOUND = "Reward not found"
ASSET_NOT_FOUND = "Asset not found"
COUPLE_NOT_FOUND = "Couple not found"
FAVORITE_NOT_FOUND = "Favorite Couple not found"
TICKET_NOT_FOUND = "Ticket not found"
ERROR_DB_CONNECT = "Something went wrong: {}"
LOCALHOST_IP = "127.0.0.1"
LINKEDIN_AUTH_LINK = "https://www.linkedin.com/oauth/v2/accessToken"
LINKEDIN_API_URL = "https://api.linkedin.com/v2"
LIST_12H = [0,12]
LIST_6H = [0, 6 , 12, 18]
LIST_4H = [0, 4, 8, 12, 16, 20]
LIST_2H = [0, 2 ,4 ,6,8,10,12,14,16,18,20,22]