FROM node:12-alpine as builder

ARG NODE_ENV='development'

ARG API_URL='https://api-predict-market-staging.hairun-technology.com'

ENV BASE_URL='https://predict-market-staging.hairun-technology.com'

WORKDIR /app/

COPY package*.json ./

COPY yarn.lock ./

RUN yarn install || true

COPY . .

RUN yarn run build

FROM nginx:stable-alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY config/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
