version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - .env.db
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    networks:
      - predict-market

  adminer:
    image: adminer
    restart: on-failure
    labels:
      traefik.frontend.rule: Host:adminer-predict.hairun-technology.com
      traefik.enable: true
      traefik.port: 8080
      traefik.frontend.entryPoints: https,http
      traefik.frontend.redirect.entryPoint: https
    networks:
      - predict-market

  api:
    image: gitlab.leviatan.fr:5050/predict-market/api/staging/api-predict:staging
    restart: always
    labels:
      traefik.frontend.rule: Host:api-predict-market-staging.hairun-technology.com
      traefik.enable: true
      traefik.port: 8000
      traefik.frontend.entryPoints: https,http
      traefik.frontend.redirect.entryPoint: https
    env_file:
      - .env.api
    depends_on:
      - db
    volumes:
      - ./static/images/symbol_crypto:/usr/src/app/static/images/symbol_crypto
      - ./static/images/user_profile:/usr/src/app/static/images/user_profile
    networks:
      - predict-market

networks:
  predict-market:
    external:
      name: traefik_predictmarket-staging
